MyWebSite/Areas/Admin/Controllers/HomeDataController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWebSite.Data.Models;
using MyWebSite.HorizontalClasses.Interfaces;
using System.Threading.Tasks;

namespace MyWebSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeDataController : Controller
    {
        private readonly IRepositoriesHundler _repos;
        private readonly IMapper _mapper;

        public HomeDataController(IRepositoriesHundler repos, IMapper mapper)
        {
            this._repos = repos;
            this._mapper = mapper;
        }

        // GET: Admin/HomeData
        public async Task<IActionResult> Index()
        {
            return View(await this._repos.HomeData.GetAll());
        }

        // GET: Admin/HomeData/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var homeData = await this._repos.HomeData.Get(id);
            if (homeData == null)
            {
                return NotFound();
            }
            return View(homeData);
        }

        // GET: Admin/HomeData/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/HomeData/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [System.Obsolete]
        public async Task<IActionResult> Create(HomeData homeData, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                // Get File
                //var files = Request.Form.Files;
                homeData.File = file;
                await this._repos.HomeData.Add(homeData);
                await this._repos.HomeData.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(homeData);
        }

        // GET: Admin/HomeData/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var homeData = await this._repos.HomeData.Get(id);
            if (homeData == null)
            {
                return NotFound();
            }
            return View(homeData);
        }

        // POST: Admin/HomeData/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [System.Obsolete]
        public async Task<IActionResult> Edit(HomeData homeData, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    homeData.File = file;
                    this._repos.HomeData.Update(homeData);
                    await this._repos.HomeData.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await HomeDataExists(homeData.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(homeData);
        }

        // GET: Admin/HomeData/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            var homeData = await this._repos.HomeData.Get(id);
            if (homeData == null)
                return NotFound();
            return View(homeData);
        }

        // POST: Admin/HomeData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [System.Obsolete]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this._repos.HomeData.Delete(id);
            await this._repos.HomeData.Save();
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> HomeDataExists(int id)
        {
            return (await this._repos.HomeData.Get(id)) != null;
        }
    }
}

MyWebSite/Areas/Admin/Controllers/ImagesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyWebSite.Data.Models;
using MyWebSite.Data.ViewModels;
using MyWebSite.HorizontalClasses.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyWebSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ImagesController : Controller
    {
        private readonly IRepositoriesHundler _repos;
        private readonly IMapper _mapper;
        private readonly IEmailTool _emailTool;

        public ImagesController(IRepositoriesHundler repos, IMapper mapper, IEmailTool emailTool)
        {
            this._repos = repos;
            this._mapper = mapper;
            this._emailTool = emailTool;
        }

        // GET: Admin/Images
        public async Task<IActionResult> Index()
        {
            List<ImageViewModel> viewModels = new List<ImageViewModel>();
            foreach(var image in await this._repos.Images.GetAll())
            {
                viewModels.Add(this._mapper.Map<ImageViewModel>(image));
            }
            return View(viewModels);
        }

        // GET: Admin/Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await this._repos.Images.Get(id);
            if (image == null)
            {
                return NotFound();
            }
            var viewModel = this._mapper.Map<ImageViewModel>(image);
            return View(viewModel);
        }

        // GET: Admin/Images/Create
        public async Task<IActionResult> Create()
        {
            ViewData["ProjectId"] = new SelectList(await this._repos.Projects.GetAll(), "ID", "Title");
            return View();
        }

        // POST: Admin/Images/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ImageViewModel viewModel)
        {
            var image = this._mapper.Map<Image>(viewModel);
            if (ModelState.IsValid)
            {
                await this._repos.Images.Add(image);
                await this._repos.Images.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(await this._repos.Projects.GetAll(), "ID", "Title", image.ProjectId);
            return View(image);
        }

        // GET: Admin/Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await this._repos.Images.Get(id);
            if (image == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(await this._repos.Projects.GetAll(), "ID", "Title", image.ProjectId);
            var viewModel = this._mapper.Map<ImageViewModel>(image);
            return View(viewModel);
        }

        // POST: Admin/Images/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ImageViewModel viewModel)
        {
            var image = this._mapper.Map<Image>(viewModel);
            if (id != image.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this._repos.Images.Update(image);
                    await this._repos.Images.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await ImageExists(image.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(await this._repos.Projects.GetAll(), "ID", "Title", image.ProjectId);
            return View(image);
        }

        // GET: Admin/Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var image = await this._repos.Images.Get(id);
            if (image == null)
            {
                return NotFound();
            }
            var viewModel = this._mapper.Map<ImageViewModel>(image);
            return View(viewModel);
        }

        // POST: Admin/Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this._repos.Images.Delete(id);
            await this._repos.Images.Save();
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ImageExists(int id)
        {
            return await this._repos.Images.Get(id) != null;
        }
    }
}

MyWebSite/Areas/Admin/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWebSite.Data.Models;
using MyWebSite.Data.ViewModels;
using MyWebSite.HorizontalClasses.Interfaces;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrdersController : Controller
    {
        private readonly IRepositoriesHundler _repos;
        private readonly IMapper _mapper;
        private readonly IEmailTool _emailTool;

        public OrdersController(IRepositoriesHundler repos, IMapper mapper, IEmailTool emailTool)
        {
            this._repos = repos;
            this._mapper = mapper;
            this._emailTool = emailTool;
        }

        // GET: Admin/Orders
        public async Task<IActionResult> Index()
        {
            return View(await this._repos.Orders.GetAll());
        }

        // GET: Admin/Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = await this._repos.Orders.Get(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // GET: Admin/Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Orders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderViewModel viewModel)
        {
            var order = this._mapper.Map<Order>(viewModel);
            if (ModelState.IsValid)
            {
                await this._repos.Orders.Add(order);
                await this._repos.Orders.Save();
                // Send Email
                // await this._emailTool.Send("body message", "Subject", "Title", "from email", "from password", "to email");
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = await this._repos.Orders.Get(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Admin/Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(OrderViewModel viewModel)
        {
            var order = this._mapper.Map<Order>(viewModel);
            if (ModelState.IsValid)
            {
                try
                {
                    this._repos.Orders.Update(order);
                    await this._repos.Orders.Save();
                    // Send Email
                    // await this._emailTool.Send("body message", "Subject", "Title", "from email", "from password", "to email");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = await this._repos.Orders.Get(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Admin/Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await this._repos.Orders.Delete(id);
            await this._repos.Orders.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return this._repos.Orders.GetAllQueryable().Any(e => e.ID == id);
        }
    }
}

MyWebSite/Areas/Admin/Views/Shared/_AdminFooter.cshtml
<footer class="footer-admin">
    &copy; @DateTime.Now.ToString().Split(" ")[0].Split("/")[2] - Alexandros Platanios
</footer>

MyWebSite/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/img/title.ico">
    <title>Alexandros Platanios</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome-free-5.15.4-web/css/all.min.css" />
    <!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="/lib/DataTables/datatables.min.css">
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("styles", required: false)
</head>

<body>
    <header>
        @{
            Html.RenderPartial("~/Areas/Admin/Views/Shared/_AdminNavBar.cshtml");
        }
    </header>

    <div class="container main">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <br />

    @{ Html.RenderPartial("~/Areas/Admin/Views/Shared/_AdminFooter.cshtml"); }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/fontawesome-free-5.15.4-web/js/all.min.js"></script>

    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="/lib/DataTables/datatables.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

MyWebSite/Areas/Admin/Views/Shared/_AdminNavBar.cshtml
@using MyWebSite.Areas.Identity.Data
@inject SignInManager<MyWebSiteUser> SignInManager
@inject UserManager<MyWebSiteUser> UserManager

<style>
    .navbar {
        min-height: 157px !important;
        margin-bottom: 1%;
    }

    .nav-item:hover {
        opacity: 0.4;
    }

    ul {
        display: inline-flex;
        flex-wrap: wrap;
        text-align: center;
    }

    li {
        text-align: center;
    }

    a {
        margin: 0 auto !important;
        font-size: large;
        font-weight: 900;
    }

    .admin-buttons {
        color: darkred !important;
    }

    .logoutbutton {
        margin: 0 auto !important;
        font-size: large;
        font-weight: 900;
    }

    .navbar-toggler {
        position: absolute;
        right: 7px;
        top: 111px;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="row" style="min-width: 277px;">
        <div class="col-md-2">
            <svg height="70" width="70">
                <polygon points="25 10, 50 60, 0 60" fill="#17539B" stroke="black" stroke-width="1" />
            </svg>
        </div>
        <div class="col-md-10">
            <a class="navbar-brand" href="/Home/Index"><b>Alexandros Platanios</b></a>
            <p><i style="color: #17539B;">Software Developer</i></p>
        </div>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="margin-left: 30px; min-width: 333px;">
            <li class="nav-item">
                <a class="nav-link text-dark" href="/Home/Resume">Resume</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="/Home/Portofolio">Portofolio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="/Home/Contact">Contact</a>
            </li>
            @if (SignInManager.IsSignedIn(User))
            {
                <li class="nav-item">
                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" method="post">
                        <button type="submit" class="nav-link btn btn-link text-dark logoutbutton">Logout</button>
                    </form>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                </li>
            }       
        </ul>
        <br/>
        <ul class="navbar-nav mr-auto" style="margin-left: 30px; min-width: 333px;">
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="HomeData" asp-action="Index">Home Data</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="ContactData" asp-action="Index">Contact Data</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="Cvs" asp-action="Index">CVs</a>
            </li>
            <li class="nav-item" style="display: none;">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="Images" asp-action="Index">Images</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="Messages" asp-action="Index">Messages</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="Projects" asp-action="Index">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="Orders" asp-action="Index">Orders</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="MyWebSiteUsers" asp-action="Index">Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark admin-buttons" asp-area="Admin" asp-controller="MyWebSiteRoles" asp-action="Index">Roles</a>
            </li>
        </ul>
    </div>
</nav>

@section scripts {

    <script>
        $(document).ready(function () {

            // Save Clicked Tab on Brouser Memmory
            $(".nav-item").on("click", function () {
                //$("a").find(".active").removeClass("active");
                //$(this).children().addClass("active");
                //$(this).children().css("color", "green");
            });

        });
    </script>
}

MyWebSite/Areas/Admin/Views/Shared/_Footer.cshtml
<style>
    .fa-facebook {
        color: #0078FF;
    }
    .fa-instagram {
        color: #B900FF;
    }
    .fa-linkedin {
        color: #1DE7FF;
    }
    .social:hover {
        opacity: 0.4 !important;
    }
    .footer {
        min-width: 541px;
        text-align: center;
    }
    @@media screen and (max-height: 990px) {
        .footer {
            margin-left: 11%;
        }
    }
</style>


<footer class="footer">
    <div class="container" style="margin: 0 auto;">
        <div class="row">
            <div class="col-lg-3">
                <strong>Phone</strong><br />
                <i>+30-6949277783</i>
            </div>
            <div class="col-lg-3">
                <strong>Email</strong><br />
                <i>alexandrosplatanios28@gmail.com</i>
            </div>
            <div class="col-lg-3">
                <strong>Follow Me</strong><br />
                <a href="https://www.facebook.com/profile.php?id=100013059701658" target="_black"><i class="fab fa-facebook fa-2x social"></i></a>
                <a href="https://www.instagram.com/alexandros_platanios/" target="_black"><i class="fab fa-instagram fa-2x social"></i></a>
                <a href="https://www.linkedin.com/in/alexandros-platanios-723984203/" target="_black"><i class="fab fa-linkedin fa-2x social"></i></a>
            </div>
            <div class="col-lg-3">
                <div style="margin-top: 11%;">
                    &copy; @DateTime.Now.ToString().Split(" ")[0].Split("/")[2] - Alexandros Platanios
                </div>
            </div>
        </div>
    </div>
</footer>

MyWebSite/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/img/title.ico">
    <title>Alexandros Platanios</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome-free-5.15.4-web/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("styles", required: false)


</head>


<body>

    <header>
        <partial name="_NavBar" />
        <partial name="_SideNavBar" />
    </header>

    


    <div class="main">
        @RenderBody()
    </div>


    <br />

    <partial name="_Footer" />


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/fontawesome-free-5.15.4-web/js/all.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

MyWebSite/Areas/Admin/Views/Shared/_NavBar.cshtml
<style>
    .nav-item:hover {
        opacity: 0.4;
    }
</style>










<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div>
        <svg height="50" width="50">
            @*<circle cx="25" cy="22" r="15" fill="#A9ABAC" />*@
            <polygon points="25 0, 50 50, 0 50" fill="#A9ABAC" stroke="black" stroke-width="1" />
        </svg>
        <a class="navbar-brand" href="/Home/Index"><b>Alexandros Platanios</b></a>
        <br />
        <i>Software Developer</i>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="margin-left: 67%;">
            <li class="nav-item">
                <a class="nav-link text-dark" href="/Home/Resume">Resume</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="/Home/Portofolio">Portofolio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="/Home/Contact">Contact</a>
            </li>
        </ul>
        @*<partial name="_LoginPartial" />*@
    </div>
</nav>











@section scripts {

    <script>
        $(document).ready(function () {

            // Save Clicked Tab on Brouser Memmory
            $(".nav-item").on("click", function () {
                //$("a").find(".active").removeClass("active");
                //$(this).children().addClass("active");
                //$(this).children().css("color", "green");
            });

        });
    </script>
}

MyWebSite/Areas/Admin/Views/Shared/_SideNavBar.cshtml
<link rel="stylesheet" href="~/css/AdminSideNavBar.css" />

<div class="sidenav navbar-light bg-light card">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="HomeData" asp-action="Index">Home Data</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ContactData" asp-action="Index">Contact Data</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Cvs" asp-action="Index">CVs</a>
        </li>
        <li class="nav-item" style="display: none;">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Images" asp-action="Index">Images</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Messages" asp-action="Index">Messages</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Projects" asp-action="Index">Projects</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Orders" asp-action="Index">Orders</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="MyWebSiteUsers" asp-action="Index">Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Admin" asp-controller="MyWebSiteRoles" asp-action="Index">Roles</a>
        </li>
    </ul>
</div>

<script src="~/js/AdminSideNavBar.js"></script>