MyWebSite/Areas/Admin/Controllers/MyWebSiteUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWebSite.Areas.Identity.Data;
using MyWebSite.Areas.Identity.Repositories;
using MyWebSite.Areas.Identity.Repositories.Interfaces;
using System;
using System.Threading.Tasks;

namespace MyWebSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MyWebSiteUsersController : Controller
    {
        private readonly UsersRepository _Users;
        private readonly RolesRepository _Roles;

        public MyWebSiteUsersController(IUsersRepository users, IRolesRepository roles)
        {
            this._Users = (UsersRepository)users;
            this._Roles = (RolesRepository)roles;
        }

        // GET: Admin/MyWebSiteUsers
        public async Task<IActionResult> Index()
        {
            return View(await this._Users.GetAll());
        }

        // GET: Admin/MyWebSiteUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var myWebSiteUser = await this._Users.Get(id);
            if (myWebSiteUser == null)
            {
                return NotFound();
            }
            ViewBag.Roles = await this._Users.GetRoles(myWebSiteUser);
            return View(myWebSiteUser);
        }

        // GET: Admin/MyWebSiteUsers/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Roles = await this._Roles.GetAll();
            return View();
        }

        // POST: Admin/MyWebSiteUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MyWebSiteUser user)
        {
            if (ModelState.IsValid)
            {
                if (user.Password == user.ConfingPassword)
                {
                    await this._Users.Add(user, user.Password);
                    // Add Roles
                    if (user.SelectedRolesIds != null && user.SelectedRolesIds.Count > 0)
                    {
                        foreach (var roleId in user.SelectedRolesIds)
                        {
                            var role = await this._Roles.Get(roleId);
                            await this._Users.AddToRole(user, role);
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.Error = "Enter your password again.";
            }
            return View(user);
        }

        // GET: Admin/MyWebSiteUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var myWebSiteUser = await this._Users.Get(id);
            if (myWebSiteUser == null)
            {
                return NotFound();
            }
            ViewBag.Roles = await this._Users.GetOtherRoles(myWebSiteUser);
            ViewBag.MyRoles = await this._Users.GetRoles(myWebSiteUser);
            return View(myWebSiteUser);
        }

        // POST: Admin/MyWebSiteUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MyWebSiteUser user)
        {
            if (user.SelectedRolesIds != null && user.SelectedRolesIds.Count > 0)
            {
                foreach (var roleId in user.SelectedRolesIds)
                {
                    var role = await this._Roles.Get(roleId);
                    try
                    {
                        await this._Users.AddToRole(user, role);
                    } catch (InvalidOperationException) { }
                }
            }
            if (user.SelectedRolesForDeleteIds != null && user.SelectedRolesForDeleteIds.Count > 0)
            {
                foreach (var roleId in user.SelectedRolesForDeleteIds)
                {
                    var role = await this._Roles.Get(roleId);
                    try
                    {
                        await this._Users.RemoveFromRole(user, role);
                    }
                    catch (InvalidOperationException) { }
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await this._Users.Update(user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await MyWebSiteRoleExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //catch (InvalidOperationException) { }
                return RedirectToAction(nameof(Index));
            }

            return View(user);
        }

        // GET: Admin/MyWebSiteUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var myWebSiteUser = await this._Users.Get(id);
            if (myWebSiteUser == null)
            {
                return NotFound();
            }
            return View(myWebSiteUser);
        }

        // POST: Admin/MyWebSiteUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await this._Users.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MyWebSiteRoleExists(string id)
        {
            return (await this._Users.Get(id)) != null;
        }
    }
}

MyWebSite/Areas/Admin/Views/MyWebSiteUsers/Create.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteUser

@{
    ViewData["Title"] = "Create";
}




<h1>Create</h1>


<h4>MyWebSiteRole</h4>
<hr />
<div class="row">
    <div class="col-md-9">
        <form asp-action="Create">
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" type="password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfingPassword" class="control-label"></label>
                        <input asp-for="ConfingPassword" class="form-control" type="password" />
                        <span asp-validation-for="ConfingPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <span class="text-danger">@ViewBag.Error</span>
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SelectedRolesIds" class="control-label"></label>
                        <select asp-for="SelectedRolesIds" class="form-control" asp-items='new SelectList(@ViewBag.Roles,"Id","Name")'>
                        </select>
                        <span asp-validation-for="SelectedRolesIds" class="text-danger"></span>
                    </div>
                    <div class="return">
                        <a asp-area="Admin" asp-controller="MyWebSiteUsers" asp-action="Index">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<br/>






@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyWebSite/Areas/Admin/Views/MyWebSiteUsers/Delete.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteUser

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MyWebSiteRole</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyWebSite/Areas/Admin/Views/MyWebSiteUsers/Details.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteUser

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MyWebSiteRole</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Roles")
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach (var role in ViewBag.Roles)
                {
                    <li>@role.Name</li>
                }
            </ul>
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyWebSite/Areas/Admin/Views/MyWebSiteUsers/Edit.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteUser

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MyWebSiteRole</h4>
<hr />
<div class="row">
    <div class="col-md-9">
        <form asp-action="Edit">
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <dl class="row">
                            <dt class="col-lg-5">
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </dt>
                            <dd class="col-lg-7">
                                @Html.DisplayFor(model => model.CreatedDate)
                            </dd>
                            <dt class="col-lg-5">
                                @Html.DisplayNameFor(model => model.LastUpdateDate)
                            </dt>
                            <dd class="col-lg-7">
                                @Html.DisplayFor(model => model.LastUpdateDate)
                            </dd>
                        </dl>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
                <div class="col-md-6">
                    <!-- Add Roles -->
                    <div class="form-group">
                        <label asp-for="SelectedRolesIds" class="control-label"></label>
                        <select asp-for="SelectedRolesIds" class="form-control" asp-items='new SelectList(@ViewBag.Roles,"Id","Name")'>
                        </select>
                        <span asp-validation-for="SelectedRolesIds" class="text-danger"></span>
                    </div>
                    <!-- Remove Roles -->
                    <div class="form-group">
                        <label asp-for="SelectedRolesForDeleteIds" class="control-label"></label>
                        <select asp-for="SelectedRolesForDeleteIds" class="form-control" asp-items='new SelectList(@ViewBag.MyRoles,"Id","Name")'>
                        </select>
                        <span asp-validation-for="SelectedRolesForDeleteIds" class="text-danger"></span>
                    </div>
                    <div>
                        <a asp-action="Index">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>






@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyWebSite/Areas/Admin/Views/MyWebSiteUsers/Index.cshtml
@model IEnumerable<MyWebSite.Areas.Identity.Data.MyWebSiteUser>

@{
    ViewData["Title"] = "Index";
}

@section styles {

}

<h1>Users</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="table-responsive" style="margin-top: 5%;">
    <table id="users-table" width="100%" class="display" cellspacing="0"></table>
    <br />
    <br />
</div>



@section Scripts{

    <script>


        $(document).ready(function () {

            var dataSet = [];
            var dataItem = [];

            @foreach (var item in Model)
            {
                @:dataItem = [];
                @:dataItem.push("@item.Id");
                @:dataItem.push("@item.Email");
                @:dataItem.push("@item.UserName");
                @:dataItem.push("@item.PhoneNumber");
                <text>
                    dataItem.push(`
                        <a asp-controller="MyWebSiteUsers" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="MyWebSiteUsers" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    `);
                </text>
                @:dataSet.push(dataItem);
            }


            $('#users-table').DataTable({
                data: dataSet,
                columns: [
                    { title: "ID" },
                    { title: "Email" },
                    { title: "UserName" },
                    { title: "Phone" },
                    null
                ],
                "pagingType": "full_numbers",
                scrollY: true,
                scrollX: true,
                "pageLength": 5,
                "lengthMenu": [[5, 10, 20, 50, 100, -1], [5, 10, 20, 50, 100, "All"]],
                "stateSave": true,
                "order": [0, 'asc'],
                //colReorder: {
                //    realtime: false
                //},
                initComplete: function (settings) {
                    $('#users-table').on('click', 'tbody td', function () {
                        var dataTable = $('#users-table').dataTable();
                        var tr = $(this).closest('tr');
                        var index = dataTable.fnGetPosition(tr[0]);
                        var id = dataTable.fnGetData(index)[0];
                        window.location.href = '/Admin/MyWebSiteUsers/Details/' + id;
                    })
                }
            });


            

        });

    </script>

}