MyWebSite/Areas/Admin/Controllers/MyWebSiteRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyWebSite.Areas.Identity.Data;
using MyWebSite.Areas.Identity.Repositories;
using MyWebSite.Areas.Identity.Repositories.Interfaces;
using System.Threading.Tasks;

namespace MyWebSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MyWebSiteRolesController : Controller
    {
        private readonly RolesRepository _Roles;
        private readonly UsersRepository _Users;

        public MyWebSiteRolesController(IUsersRepository users, IRolesRepository roles)
        {
            this._Roles = (RolesRepository)roles;
            this._Users = (UsersRepository)users;
    }

        // GET: Admin/MyWebSiteRoles
        public async Task<IActionResult> Index()
        {
            return View(await this._Roles.GetAll());
        }

        // GET: Admin/MyWebSiteRoles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var myWebSiteRole = await this._Roles.Get(id);
            if (myWebSiteRole == null)
            {
                return NotFound();
            }
            return View(myWebSiteRole);
        }

        // GET: Admin/MyWebSiteRoles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/MyWebSiteRoles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MyWebSiteRole myWebSiteRole)
        {
            if (ModelState.IsValid)
            {
                await this._Roles.Add(myWebSiteRole);
                return RedirectToAction(nameof(Index));
            }
            return View(myWebSiteRole);
        }

        // GET: Admin/MyWebSiteRoles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var myWebSiteRole = await this._Roles.Get(id);
            if (myWebSiteRole == null)
            {
                return NotFound();
            }
            return View(myWebSiteRole);
        }

        // POST: Admin/MyWebSiteRoles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MyWebSiteRole myWebSiteRole)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this._Roles.Update(myWebSiteRole);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await MyWebSiteRoleExists(myWebSiteRole.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(myWebSiteRole);
        }

        // GET: Admin/MyWebSiteRoles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var myWebSiteRole = await this._Roles.Get(id);
            if (myWebSiteRole == null)
            {
                return NotFound();
            }
            return View(myWebSiteRole);
        }

        // POST: Admin/MyWebSiteRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await this._Roles.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MyWebSiteRoleExists(string id)
        {
            return (await this._Roles.Get(id)) != null;
        }
    }
}

MyWebSite/Areas/Admin/Views/MyWebSiteRoles/Create.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteRole

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MyWebSiteRole</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyWebSite/Areas/Admin/Views/MyWebSiteRoles/Delete.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteRole

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MyWebSiteRole</h4>
    <hr />
    <dl class="row">
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.NormalizedName)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.NormalizedName)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.ConcurrencyStamp)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.ConcurrencyStamp)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyWebSite/Areas/Admin/Views/MyWebSiteRoles/Details.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteRole

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MyWebSiteRole</h4>
    <hr />
    <dl class="row">
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.NormalizedName)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.NormalizedName)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.ConcurrencyStamp)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.ConcurrencyStamp)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-lg-3">
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>
        <dd class="col-lg-9">
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyWebSite/Areas/Admin/Views/MyWebSiteRoles/Edit.cshtml
@model MyWebSite.Areas.Identity.Data.MyWebSiteRole

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MyWebSiteRole</h4>
<hr />
<div class="row">
    <div class="col-lg-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <dl class="row">
                    <dt class="col-lg-6">
                        @Html.DisplayNameFor(model => model.CreatedDate)
                    </dt>
                    <dd class="col-lg-6">
                        @Html.DisplayFor(model => model.CreatedDate)
                    </dd>
                    <dt class="col-lg-6">
                        @Html.DisplayNameFor(model => model.LastUpdateDate)
                    </dt>
                    <dd class="col-lg-6">
                        @Html.DisplayFor(model => model.LastUpdateDate)
                    </dd>
                </dl>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyWebSite/Areas/Admin/Views/MyWebSiteRoles/Index.cshtml
@model IEnumerable<MyWebSite.Areas.Identity.Data.MyWebSiteRole>

@{
    ViewData["Title"] = "Index";
}

@section styles {

}

<h1>Roles</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="table-responsive" style="margin-top: 5%;">
    <table id="roles-table" width="100%" class="display" cellspacing="0"></table>
    <br />
    <br />
</div>








@section Scripts{

    <script>


        $(document).ready(function () {

            var dataSet = [];
            var dataItem = [];

            @foreach (var item in Model)
            {
                @:dataItem = [];
                @:dataItem.push("@item.Id");
                @:dataItem.push("@item.Name");
                @:dataItem.push("@item.NormalizedName");
                @:dataItem.push("@item.ConcurrencyStamp");
                @:dataItem.push("@item.CreatedDate");
                @:dataItem.push("@item.LastUpdateDate");
                <text>
                    dataItem.push(`
                        <a asp-controller="MyWebSiteRoles" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="MyWebSiteRoles" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    `);
                </text>
                @:dataSet.push(dataItem);
            }


            $('#roles-table').DataTable({
                data: dataSet,
                columns: [
                    { title: "ID" },
                    { title: "Name" },
                    { title: "Normalized Name" },
                    { title: "Concurrency Stamp" },
                    { title: "CreatedDate" },
                    { title: "LastUpdateDate" },
                    null
                ],
                "pagingType": "full_numbers",
                scrollY: true,
                scrollX: true,
                "pageLength": 5,
                "lengthMenu": [[5, 10, 20, 50, 100, -1], [5, 10, 20, 50, 100, "All"]],
                "stateSave": true,
                "order": [0, 'asc'],
                //colReorder: {
                //    realtime: false
                //},
                initComplete: function (settings) {
                    $('#roles-table').on('click', 'tbody td', function () {
                        var dataTable = $('#roles-table').dataTable();
                        var tr = $(this).closest('tr');
                        var index = dataTable.fnGetPosition(tr[0]);
                        var id = dataTable.fnGetData(index)[0];
                        window.location.href = '/Admin/MyWebSiteRoles/Details/' + id;
                    })
                }
            });




        });

    </script>

}